server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  datasource:
    incar:
      url: jdbc:mysql://192.168.1.242:3306/incar?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      hikari:
        maximum-pool-size: 20
        minimum-idle: 10
        pool-name: IncarHikariPool
    user:
      url: jdbc:mysql://192.168.1.242:3306/service_user?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=UTF-8&generateSimpleParameterMetadata=true
      username: root
      password: root
      hikari:
        maximum-pool-size: 20
        minimum-idle: 10
        pool-name: UserHikariPool
logging:
  config: classpath:config/logback.xml

user:
  recharge-url: https://user-terminal-test.mydadao.com/oms/user/rechargeByMobile